stages:
- name: Test
  steps:
  - runScriptConfig:
      image: python:3
      shellScript: |-
        python3 -m pip install pytest
        python3 -m pip install -r requirements.txt
        pytest tests
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: skynet/youuuuuuutubedl:v2.0.0
      pushRemote: true
      registry: registry.world0:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
