apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-k8v9g
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-world0-youuuuuuutubedl
  name: youuuuuuutubedl
  namespace: world0
  selfLink: /apis/apps/v1beta2/namespaces/world0/deployments/youuuuuuutubedl
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-world0-youuuuuuutubedl
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-07-08T20:57:54Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-world0-youuuuuuutubedl
    spec:
      containers:
      - image: rancher.n7sa.com:5000/skynet/youuuuuuutubedl:v2.0.0
        imagePullPolicy: Always
        name: youuuuuuutubedl
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
